version: '3.8'
volumes:
  # the name of a volume to be used to store the database folder
  # the same is used at "- ./app_x_mysql_data:/var/lib/mysql"
  app_x_mysql_data:
    driver: local
services:
  app_x_mysql_service:
    image: mysql:latest
    container_name: app_x_mysql_database
    restart: always
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      #- MYSQL_USER=${DB_USER}
      #- MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      # the location of the database folder
      - ./app_x_mysql_data:/var/lib/mysql